# modified from https://github.com/keras-team/keras/blob/master/.travis.yml
sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 2.7
          env: KERAS_BACKEND=tensorflow
        - python: 3.6
          env: KERAS_BACKEND=tensorflow
        - python: 2.7
          env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_compile
        - python: 3.6
          env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_compile
        - python: 2.7
          env: KERAS_BACKEND=cntk PYTHONWARNINGS=ignore
        - python: 3.6
          env: KERAS_BACKEND=cntk PYTHONWARNINGS=ignore
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pandas
  - source activate test-environment
  - pip install --only-binary=numpy numpy nose cython h5py theano
  - conda install mkl mkl-service
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install pil;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      conda install Pillow;
    fi
  - pip install argparse
  - pip install -e .[tests]
  - pip install tensorflow==1.7
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.3.1-cp27-cp27mu-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.3.1-cp36-cp36m-linux_x86_64.whl;
    fi
  - if [[ "$KERAS_BACKEND" != "tensorflow" ]]; then
      echo '    keras/backend/tensorflow_backend.py' >> .coveragerc;
    fi
  - if [[ "$KERAS_BACKEND" != "theano" ]]; then
      echo '    keras/backend/theano_backend.py' >> .coveragerc;
    fi
  - if [[ "$KERAS_BACKEND" != "cntk" ]]; then
      echo '    keras/backend/cntk_backend.py' >> .coveragerc;
    fi
  - export CORE_CHANGED=False;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "keras/backend/"* ]] || [[ "$entry" == "keras/engine/"* ]] || [[ "$entry" == "keras/layers/"* ]]; then export CORE_CHANGED=True; fi; done
  - export APP_CHANGED=False;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "keras/applications/"* ]]; then export APP_CHANGED=True; fi; done
  - rm -rf ~/mpi
  - mkdir ~/mpi
  - pushd ~/mpi
  - wget http://cntk.ai/PythonWheel/ForKeras/depends/openmpi_1.10-3.zip
  - unzip ./openmpi_1.10-3.zip
  - sudo dpkg -i openmpi_1.10-3.deb
  - popd

script:
  - export MKL_THREADING_LAYER="GNU"
  - python -c "import keras.backend"
  - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
  - PYTHONPATH=$PWD:$PYTHONPATH py.test tests;

